name: CI

on:
  push:
    branches: 
      - main
      - develop
      - feature/**
    tags:        
      - v2
      - v1.*
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  ENV_NAME: "FixENV"
  
jobs:

  log:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: isMain
      if: ${{ github.ref == 'refs/heads/main' }}
      run: echo "This is a main!"
    - name: github.ref
      run: echo "${{ github.ref }}"
    - name: github.ref.name
      run: echo "${{ github.ref_name }}"
    - name: secrets.PASSWORD
      run: echo "${{ secrets.PASSWORD }}"
    - name: vars.URL
      run: echo "${{ vars.URL }}"
    - name: github.ref_name == main
      if: ${{ github.ref_name == 'main' }}
      run: echo "$ENV_NAME"

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: task
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  code-scand:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: task
      run: echo "dont"

  security-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: task
      run: echo "dont"

  unit-test:
    runs-on: ubuntu-latest
    needs: [build,code-scand,security-scan]
    steps:
    - uses: actions/checkout@v3
    - name: task
      run: echo "dont"

  deploy-alpha:
    runs-on: ubuntu-latest
    if: ${{ endsWith( github.ref, 'alpha' ) }}
    needs: [unit-test]
    steps:
    - uses: actions/checkout@v3
    - name: task
      run: echo "dont"

  deploy-staging:
    runs-on: ubuntu-latest
    if: ${{ endsWith( github.ref, 'beta' ) }}
    needs: [unit-test]
    steps:
    - uses: actions/checkout@v3
    - name: task
      run: echo "dont"

  deploy-prod:
    runs-on: ubuntu-latest
    if: ${{ endsWith( github.ref, 'prod' ) }}
    needs: [unit-test]
    steps:
    - uses: actions/checkout@v3
    - name: task
      run: echo "dont"

  sanity-alpha:
    runs-on: ubuntu-latest
    needs: [deploy-alpha]
    steps:
    - uses: actions/checkout@v3
    - name: task
      run: echo "dont"

  sanity-staging:
    runs-on: ubuntu-latest
    needs: [deploy-staging]
    steps:
    - uses: actions/checkout@v3
    - name: task
      run: echo "dont"

  sanity-prod:
    runs-on: ubuntu-latest
    needs: [deploy-prod]
    steps:
    - uses: actions/checkout@v3
    - name: task
      run: echo "dont"
